name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Login to crates.io
      run: cargo login ${{ secrets.TOKEN }}
    - name: Publish crate
      run: cargo publish
      if: contains(github.event.head_commit.message, '[publish]')
